In [1]:
from collections import defaultdict
import numpy as np
import pandas as pd
db = pd.read_csv("shoprite_dataset.csv",header = None) #THIS FUNCTION IMPORTS THE CSV FILES!!
db.fillna('Zero')

          0  1   2     3     4     5
0    Trans1  A   B     C  Zero  Zero
1    Trans2  A   B     C  Zero  Zero
2    Trans3  A   B     C     D  Zero
3    Trans4  A   B     C     D     E
4    Trans5  A   B     D     E  Zero
5    Trans6  A   D     E  Zero  Zero
6    Trans7  A   E  Zero  Zero  Zero
7    Trans8  A   E  Zero  Zero  Zero
8    Trans9  A   C     E  Zero  Zero
9   Trans10  A   C     E  Zero  Zero
10  Trans11  A   C     E  Zero  Zero
11  Trans12  B   D     F  Zero  Zero
12  Trans13  C   E     A  Zero  Zero
13  Trans14  D   F     B  Zero  Zero
14  Trans15  E   A     C  Zero  Zero
15  Trans16  F   B     D  Zero  Zero
16  Trans17  A   C     E  Zero  Zero
17  Trans18  B   D     F  Zero  Zero
18  Trans19  C   E     A  Zero  Zero
19  Trans20  D   F     B  Zero  Zero

In [2]:
db1 = db.values.tolist() #THIS FUCNTIONS CONVERTS CSV FILES INTO LISTS
db1

[['Trans1', 'A', ' B', ' C', nan, nan],
 ['Trans2', 'A', ' B', ' C', nan, nan],
 ['Trans3', 'A', ' B', ' C', ' D', nan],
 ['Trans4', 'A', ' B', ' C', ' D', ' E'],
 ['Trans5', 'A', ' B', ' D', ' E', nan],
 ['Trans6', 'A', ' D', ' E', nan, nan],
 ['Trans7', 'A', ' E', nan, nan, nan],
 ['Trans8', 'A', ' E', nan, nan, nan],
 ['Trans9', 'A', ' C', ' E', nan, nan],
 ['Trans10', 'A', ' C', ' E', nan, nan],
 ['Trans11', 'A', ' C', ' E', nan, nan],
 ['Trans12', 'B', 'D', 'F', nan, nan],
 ['Trans13', 'C', 'E', 'A', nan, nan],
 ['Trans14', 'D', 'F', 'B', nan, nan],
 ['Trans15', 'E', 'A', 'C', nan, nan],
 ['Trans16', 'F', 'B', 'D', nan, nan],
 ['Trans17', 'A', 'C', 'E', nan, nan],
 ['Trans18', 'B', 'D', 'F', nan, nan],
 ['Trans19', 'C', 'E', 'A', nan, nan],
 ['Trans20', 'D', 'F', 'B', nan, nan]]

In [3]:
for i in range(0,len(db1)): #WITH THIS FUNCTION WE CONVERT SIMPLE LISTS INTO NESTED LIST, 
                            #NESTED LISTS ARE EASIER TO PROCESS WITH THIS ALGORITHM 
    new_line=db1[i][0]
    new_line1= db1[i][1:]
    db2=[]
    db2.append(new_line)
    db2.append(new_line1)
    print(db2)

['Trans1', ['A', ' B', ' C', nan, nan]]
['Trans2', ['A', ' B', ' C', nan, nan]]
['Trans3', ['A', ' B', ' C', ' D', nan]]
['Trans4', ['A', ' B', ' C', ' D', ' E']]
['Trans5', ['A', ' B', ' D', ' E', nan]]
['Trans6', ['A', ' D', ' E', nan, nan]]
['Trans7', ['A', ' E', nan, nan, nan]]
['Trans8', ['A', ' E', nan, nan, nan]]
['Trans9', ['A', ' C', ' E', nan, nan]]
['Trans10', ['A', ' C', ' E', nan, nan]]
['Trans11', ['A', ' C', ' E', nan, nan]]
['Trans12', ['B', 'D', 'F', nan, nan]]
['Trans13', ['C', 'E', 'A', nan, nan]]
['Trans14', ['D', 'F', 'B', nan, nan]]
['Trans15', ['E', 'A', 'C', nan, nan]]
['Trans16', ['F', 'B', 'D', nan, nan]]
['Trans17', ['A', 'C', 'E', nan, nan]]
['Trans18', ['B', 'D', 'F', nan, nan]]
['Trans19', ['C', 'E', 'A', nan, nan]]
['Trans20', ['D', 'F', 'B', nan, nan]]

In [4]:
db2 = [['Trans1', ['A', ' B', ' C']]
,['Trans2', ['A', ' B', ' C']]
,['Trans3', ['A', ' B', ' C', ' D']]
,['Trans4', ['A', ' B', ' C', ' D', ' E']]
,['Trans5', ['A', ' B', ' D', ' E']]
,['Trans6', ['A', ' D', ' E']]
,['Trans7', ['A', ' E']]
,['Trans8', ['A', ' E']]
,['Trans9', ['A', ' C', ' E']]
,['Trans10', ['A', ' C', ' E']]
,['Trans11', ['A', ' C', ' E']]
,['Trans12', ['B', 'D', 'F']]
,['Trans13', ['C', 'E', 'A']]
,['Trans14', ['D', 'F', 'B']]
,['Trans15', ['E', 'A', 'C']]
,['Trans16', ['F', 'B', 'D']]
,['Trans17', ['A', 'C', 'E']]
,['Trans18', ['B', 'D', 'F']]
,['Trans19', ['C', 'E', 'A']]
,['Trans20', ['D', 'F', 'B']]]

In [5]:
init = []      # THIS FUNCTION SPECIFIES ALL THE INDIVISUAL ITEMSETS IN THE TRANSACTIONS
for i in db2:
    for q in i[1]:
        if(q not in init):
            init.append(q)

print(init)

['A', ' B', ' C', ' D', ' E', 'B', 'D', 'F', 'C', 'E']

In [14]:
support = 0.70
s = int(support*len(init))

In [15]:
from collections import Counter #THIS FUCNTION CALCULATES C1 AND L1 WITH RESPECT TO MINIMUM SUPPORT
c = Counter()
for i in init:
    for d in db2:
        if(i in d[1]):
            c[i]+=1
print("C1:")
for i in c:
    print(str([i])+": "+str(c[i]))
print()
l = Counter()
for i in c:
    if(c[i] >= s):
        l[frozenset([i])]+=c[i]
print("L1:")
for i in l:
    print(str(list(i))+": "+str(l[i]))
print()

C1:
['A']: 15
[' B']: 5
[' C']: 7
[' D']: 4
[' E']: 8
['B']: 5
['D']: 5
['F']: 5
['C']: 4
['E']: 4

L1:
['A']: 15
[' C']: 7
[' E']: 8

In [16]:
pl = l  #THIS FUCNTION IS FILLED WITH FOR LOOPS TO CONTINUOUS CALCULATE Cs AND Ls beyond C1 AND L1 UNTIL THERE IS ONLY ONE COMBINATION LEFT
pos = 1
for count in range (2,1000):
    nc = set()
    temp = list(l)
    for i in range(0,len(temp)):
        for j in range(i+1,len(temp)):
            t = temp[i].union(temp[j])
            if(len(t) == count):
                nc.add(temp[i].union(temp[j]))
    nc = list(nc)
    c = Counter()
    for i in nc:
        c[i] = 0
        for q in db2:
            temp = set(q[1])
            if(i.issubset(temp)):
                c[i]+=1
    print("C"+str(count)+":")
    for i in c:
        print(str(list(i))+": "+str(c[i]))
    print()
    l = Counter()
    for i in c:
        if(c[i] >= s):
            l[i]+=c[i]
    print("L"+str(count)+":")
    for i in l:
        print(str(list(i))+": "+str(l[i]))
    print()
    if(len(l) == 0):
        break
    pl = l
    pos = count
print("Result: ")
print("L"+str(pos)+":")
for i in pl:
    print(str(list(i))+": "+str(pl[i]))
print()
from itertools import combinations
for l in pl:
    c = [frozenset(q) for q in combinations(l,len(l)-1)]
    mmax = 0
    for a in c:
        b = l-a
        ab = l
        sab = 0
        sa = 0
        sb = 0
        for q in db2:
            temp = set(q[1])
            if(a.issubset(temp)):
                sa+=1
            if(b.issubset(temp)):
                sb+=1
            if(ab.issubset(temp)):
                sab+=1
        temp = sab/sa*100
        if(temp > mmax):
            mmax = temp
        temp = sab/sb*100
        if(temp > mmax):
            mmax = temp
        print(str(list(a))+" -> "+str(list(b))+" = "+str(sab/sa*100)+"%")
        print(str(list(b))+" -> "+str(list(a))+" = "+str(sab/sb*100)+"%")
    curr = 1
    print("choosing:", end=' ')
    for a in c:
        b = l-a
        ab = l
        sab = 0
        sa = 0
        sb = 0
        for q in db2:
            temp = set(q[1])
            if(a.issubset(temp)):
                sa+=1
            if(b.issubset(temp)):
                sb+=1
            if(ab.issubset(temp)):
                sab+=1
        temp = sab/sa*100
        if(temp == mmax):
            print(curr, end = ' ')
        curr += 1
        temp = sab/sb*100
        if(temp == mmax):
            print(curr, end = ' ')
        curr += 1
    print()
    print()

C2:
[' E', ' C']: 4
['A', ' E']: 8
['A', ' C']: 7

L2:
['A', ' E']: 8
['A', ' C']: 7

C3:
[' C', 'A', ' E']: 4

L3:

Result:
L2:
['A', ' E']: 8
['A', ' C']: 7

['A'] -> [' E'] = 53.333333333333336%
[' E'] -> ['A'] = 100.0%
[' E'] -> ['A'] = 100.0%
['A'] -> [' E'] = 53.333333333333336%
choosing: 2 3

['A'] -> [' C'] = 46.666666666666664%
[' C'] -> ['A'] = 100.0%
[' C'] -> ['A'] = 100.0%
['A'] -> [' C'] = 46.666666666666664%
choosing: 2 3

In [17]:
from itertools import combinations
for l in pl:
    c = [frozenset(q) for q in combinations(l,len(l)-1)]
    mmax = 0
    for a in c:
        b = l-a
        ab = l
        sab = 0
        
        sa = 0
        sb = 0
        for q in db2:
            temp = set(q[1])
            if(a.issubset(temp)):
                sa+=1
            if(b.issubset(temp)):
                sb+=1
            if(ab.issubset(temp)):
                sab+=1
        temp = sab/sa*100
        if(temp > mmax):
            mmax = temp
        temp = sab/sb*100
        if(temp > mmax):
            mmax = temp
        print(str(list(a))+" -> "+str(list(b))+" = "+str(sab/sa*100)+"%")
        print(str(list(b))+" -> "+str(list(a))+" = "+str(sab/sb*100)+"%")
    curr = 1
    print("choosing:", end=' ')
    for a in c:
        b = l-a
        ab = l
        sab = 0
        sa = 0
        sb = 0
        for q in db2:
            temp = set(q[1])
            if(a.issubset(temp)):
                sa+=1
            if(b.issubset(temp)):
                sb+=1
            if(ab.issubset(temp)):
                sab+=1
        temp = sab/sa*100
        if(temp == mmax):
            print(curr, end = ' ')
        curr += 1
        temp = sab/sb*100
        if(temp == mmax):
            print(curr, end = ' ')
        curr += 1
    print()
    print()

['A'] -> [' E'] = 53.333333333333336%
[' E'] -> ['A'] = 100.0%
[' E'] -> ['A'] = 100.0%
['A'] -> [' E'] = 53.333333333333336%
choosing: 2 3

['A'] -> [' C'] = 46.666666666666664%
[' C'] -> ['A'] = 100.0%
[' C'] -> ['A'] = 100.0%
['A'] -> [' C'] = 46.666666666666664%
choosing: 2 3